#!/usr/bin/env bash
# Panel Caddy vhost snippet (localhost tunnel default).
set -euo pipefail

CADDY_CONFD="${CADDY_CONFD:-/etc/caddy/conf.d}"
CADDYFILE='/etc/caddy/Caddyfile'

caddy_port_listening() {
    local p="$1"
    ss -tln 2>/dev/null | awk '{print $4}' | grep -Eq ":${p}$"
}

configure_panel_caddy() {
    [[ "${SKIP_CADDY:-0}" -eq 0 ]] || { echo "Caddy snippet skipped"; return 0; }
    echo "==> Configuring panel Caddy vhost on 127.0.0.1:${PANEL_PORT}"

    install -d -m 0755 -o "${WEB_USER}" -g "${WEB_USER}" /var/log/caddy
    touch /var/log/caddy/access_azerioid-panel.log
    chown "${WEB_USER}:${WEB_USER}" /var/log/caddy/access_azerioid-panel.log
    chmod 0640 /var/log/caddy/access_azerioid-panel.log

    install -d -m 0755 "${CADDY_CONFD}"
    local snippet="${CADDY_CONFD}/azerioid-panel.conf"
    python3 - "${snippet}" "${PREFIX}" "${PANEL_PORT}" <<'PY'
import pathlib, sys
snippet, prefix, port = sys.argv[1:4]
web = prefix + "/web/public"
sock = "unix//run/php/azerioid-panel.sock"
text = f"""# Stack Manager panel vhost (generated by install.sh)
http://127.0.0.1:{port} {{
    bind 127.0.0.1
    encode gzip zstd
    root * {web}
    php_fastcgi {sock}
    file_server
    header {{
        X-Content-Type-Options nosniff
        X-Frame-Options DENY
        Referrer-Policy no-referrer
        -Server
    }}
    log {{
        output file /var/log/caddy/access_azerioid-panel.log {{
            roll_size 16mb
            roll_keep 3
            roll_keep_for 7d
        }}
    }}
}}
"""
pathlib.Path(snippet).write_text(text)
PY
    chmod 0644 "${snippet}"

    if [[ ! -f "${CADDYFILE}" ]]; then
        install -d -m 0755 /etc/caddy
        cat > "${CADDYFILE}" <<'EOF'
{
    admin off
}
import /etc/caddy/conf.d/*.conf
EOF
        chown root:root "${CADDYFILE}"
    fi

    if command -v caddy >/dev/null 2>&1; then
        caddy validate --config "${CADDYFILE}" || { echo "Caddy validate failed" >&2; return 1; }
        systemctl enable --now caddy 2>/dev/null || true
        systemctl reload caddy 2>/dev/null || systemctl restart caddy 2>/dev/null || true
    fi

    local i
    for i in $(seq 1 30); do
        caddy_port_listening "${PANEL_PORT}" && return 0
        sleep 0.3
    done
    echo "Warning: port ${PANEL_PORT} not listening after Caddy reload" >&2
}
